spring:
  application:
    name: order-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: mongodb://aman:aman@localhost:27017/db?authSource=admin

server:
  port: 8100


queue:
  order-created: ORDER_CREATED_EVENT
  order-done: ORDER_DONE_EVENT
  order-canceled: ORDER_CANCELED_EVENT

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/